# Generated by Django 4.1.5 on 2023-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_object',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
