# Generated by Django 4.1.5 on 2023-12-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_recipe_is_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_object',
            new_name='ingr_is_object',
        ),
    ]
