# Generated by Django 4.1.5 on 2023-12-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_rename_is_object_recipe_ingr_is_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingr_is_object',
            new_name='ingredients_is_object',
        ),
    ]
