# Generated by Django 4.1.5 on 2023-12-12 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_rename_ingr_is_object_recipe_ingredients_is_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField()),
                ('main_meal', models.BooleanField()),
                ('snack', models.BooleanField()),
                ('desert', models.BooleanField()),
                ('salad', models.BooleanField()),
                ('soup', models.BooleanField()),
                ('other', models.BooleanField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipe', to='cookbook.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
