# Generated by Django 4.1.5 on 2024-04-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
